version: '3'

networks:
  my-network:
    driver: bridge

services:
  postgres:
    networks:
      - my-network
    image: 'postgres:11'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  webapp:
    networks:
      - my-network
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
